### ISSUE TITLE
Middle Earth Map Owner Team

### ISSUE THREAD

**Issue by alkexr** [triplea-maps/Project#2]
I don't really know where I am actually, but I followed a link with the intention of leaving a list of maps I authored, which is 1 map:
Large_Middle_Earth
So I submit this issue or what and see what happens. Sorry if I mess up something.

**Comment by williamdekryger** [comment]
@alkexr You are in the right place. Thanks for the info. You were exactly right.

**Comment by DanVanAtta** [comment]
Middle earth team created, an invite has been sent to you @alkexr

**Comment by DanVanAtta** [comment]
middle_earth map recently uploaded:  https://github.com/triplea-maps/middle_earth

If you'd like to make modifications to the map, here is a tutorial to help you get started with git: http://github.com/triplea-maps/Project/wiki/Map-Makers:-Setup-Instructions

Otherwise sit back and enjoy ownership. If anyone wants to update the map other than admins, you'll get an email asking you to approve the update. Otheriwse you'll get occasional emails from issues that may come up.

That issue queue will be at: https://github.com/triplea-maps/middle_earth/issues

Also be aware you have a wiki you can use if you'd like:
https://github.com/triplea-maps/middle_earth/wiki

Otherwise zip files of the map will be available here:
https://github.com/triplea-maps/middle_earth/releases

**Comment by alkexr** [comment]
No, no. I have been added to the original middle earth map that comes with the game, which is not my map. My map is called exactly "Large_Middle_Earth", with one game: "Large Middle Earth - Third Age All Stars".
