### ISSUE TITLE
Please Create Map Repo "Roll Through The Reich"

### ISSUE THREAD

**Issue by m3tan** [triplea-maps/Project#22]
Please create an empty shell repository. Thank you.

**Comment by DanVanAtta** [comment]
Created: https://github.com/triplea-maps/roll_through_the_reich

Accept the team invite: https://github.com/orgs/triplea-maps/teams/m3tan, to gain admin control of that repo.

I will create the automated travis part hopefully later tonight, but might be a day or two..

**Comment by DanVanAtta** [comment]
please re-open if you start using the repo and want the travis support.

**Comment by m3tan** [comment]
Can you please reopen this? Somehow I missed a step in the process. I thought I was waiting on you to setup the map repo for me. Can you send me instructions or an online link as to what I'm supposed to do next? Sorry I'm a newbie and bit lost in this process...
Thanks,
Mike

Date: Sun, 24 Jul 2016 15:44:27 -0700

**Comment by DanVanAtta** [comment]
You're the first to start with a fresh repo, and not a map zip. This case could use some scripted support, #34 . Specifically we have a script to set up a repo from zip, but we need to do this work.

@m3tan We've also made some updates that make the travis script less necessary. You can clone the map repo directly to 'downloadedMaps' in the triplea folder, and the game will pick it up. Note also in the settings window you can control which folder is used for maps, so you can have multiple versions of your maps. 

The travis setup is very nice for very easy sharing.. with some luck we will have that component in place soon.

**Comment by m3tan** [comment]
I tried to upload my map and the first error message was that I could not select more than 100 files. Then I zipped the map (48MB) and tried to upload it, and it said the file was too large. I feel like I'm doing this all wrong. How do I just upload my map for others to download?

Date: Tue, 9 Aug 2016 18:46:32 -0700

**Comment by DanVanAtta** [comment]
Try uploading a few folders at a time. Please do not upload the zip file, it will not work. We need a specific folder structure to be posted, namely a "maps" folder at the root that then contains the standard map folders/files.

**Comment by DanVanAtta** [comment]
@m3tan , with this update: https://github.com/triplea-game/triplea/pull/1164, you will not need a travis script anymore, having a github repo with the right folder format is all you will need (and the repo needs to named all lower case with underscores, second condition). 

With some luck I'll have some documentation set up soon..

**Comment by DanVanAtta** [comment]
@m3tan  the simplified update has gone through. You can use this URL: https://github.com/triplea-maps/roll_through_the_reich/archive/master.zip to download the map.

Please submit a PR to update this fiel: https://github.com/triplea-maps/Project/blob/master/production_config/triplea_maps.yaml, with a description and the above link, and the map will become available for in-game download.

With luck the docs are going to be improved to cover this process more cleanly: https://github.com/triplea-game/triplea/tree/master/docs, it's still new, so still figuring out how to streamline the process.

Closing since the map repo is fully set up now :+1:  

https://github.com/triplea-maps/roll_through_the_reich
