### ISSUE TITLE
Could you inform me about uploading procedures

### ISSUE THREAD

**Issue by Navalland** [triplea-maps/Project#69]
I am new at github I found this is too complex platform so I want to upload my map to map repository.

**Comment by simon33-2** [comment]
You can (theoretically) upload your map anywhere you like but if the triplea-maps.yaml file doesn't refer to it no one will be able to see it without installing on their computer manually.

What part in particular causes you grief? Are we talking about a brand new set of maps here? I would guess that is best sorted by getting a new repo to which you have write access. You would need an admin to do that for you.

**Comment by beelee1** [comment]
I have a map that is only in my own downloaded maps file. I created a repository and started uploading files. As mentioned in the upload instructions if the file is too big you need to use multiple folders.

I assume all map folders are too big since it can only handle less than 100 files at a time. Anyway what's the best way to do this ? Everything except baseTiles, misc, reliefTiles and units is uploaded. I was going to create as many sub folders as necessary naming them 1,2,3, etc... Do they then need to be reconfigured so it looks the same as when I started ? If so how do I do that ?

I must say this strikes me as rather labor intensive.

Also need help about how to put it in triplea- maps. It looks as if I have to have my repository change ownership ? 

This is Ozteas 1941 global setup so it's not really a completely new map. Point is I have tested extensively and it works correctly. Any help would be appreciated.

Thanks

**Comment by panther2** [comment]
> I assume all map folders are too big since it can only handle less than 100 files at a time. Anyway what's the best way to do this ?

In case you want to use the web interface for uploading simply select the first 100 files to upload; when done select the next 100 files and so on until you are done. Works pretty nice this way.

**Comment by beelee1** [comment]
Thanks panther2 I'll see if I can figure that out.

**Comment by beelee1** [comment]
When I add the games folder 3 xmls show up instead of 1. First one is different, second one is correct with colored text and third one is correct with no coloring. Should I delete first and third ?

**Comment by beelee1** [comment]
Ok I finally battled my way through that step and have map in a repository. If you're new to this I would suggest staying away from the click n drag method. 

Anyway do I just type in triplea-maps in the transfer spot ?

**Comment by panther2** [comment]
It is better to delete the xml files that are not needed.

> Anyway do I just type in triplea-maps in the transfer spot ?
Please explain what you want to do, as I am not sure what you are asking here...

**Comment by beelee1** [comment]
Changing the repo at github. The triplea-maps/project/mapmaking tools readme said I should ask here for guidance.

I'm trying to get Ozteas 41 setup for global on the dl maps list. The map plays fine but I know I have a few more steps to go through.

**Comment by panther2** [comment]
Compared to Global 2nd Edition: Is it only a different setup or are there other differences, such as other nations, other units, other territories, other gameplay or anything else? Maybe it is enough to just add the xml?

**Comment by beelee1** [comment]
No just the xml. That'd be the best place for it. I know it's fairly popular with people. I don't know if the global people would want it in there if it hasn't been tested by the community though.

I had it working for 1.8 but never put it on triplea. I've playtested it close to three years now and I'm fairly confident I've caught all the bugs. I've tested for a couple months since updating to 1.9,  but it's possible I missed something.

Maybe it could run on it's own for a while and then merge it to the global maps if the global people don't want it in there right now ?

I'm not to familiar with the whole process.

**Comment by panther2** [comment]
If you wanted to bring a new map to this project, the project admins would need to create a new repository within github.com/triplea-maps/... 

As in this case only the xml has changed, IMHO it would not make sense to have all those redundant files again in a new repo. As we already have non-OOB xml's inside the Global repo (for example the so called Balanced mod or turn sequence changes) your new additional xml would not be that exotic. On the other hand it is discussable how many xml-files we want to add to maps, as all of them need to be adjusted, when general changes occur.

Maybe it is time that @ron-murhammer  or @DanVanAtta add their opinion here.

**Comment by beelee1** [comment]
Sounds good Panther. Oz has a 42 that I'll probably convert at some time as well. That's it though. It'd be cool to be with the other globals as people would probably see it more. Not that big of deal either way though. As long as it's inside the game, people can find it easy enough.

**Comment by panther2** [comment]
I can offer you my assistance when it comes to just adding your xml to the present Global repo, if you want/need...

**Comment by beelee1** [comment]
Way cool Panther ! I'll be gone for a few days, but yea I'd like to do that. I think people will definitely play it, so yea lets do it.

Just to save my uneducated self some time, would you line me out with some 1,2,3,4 type steps to do ? I know I'll figure it out eventually, but I don't really see the big picture. It took me 12 hours and 10 minutes to upload the map. I'm sure it'll take more than 10 minutes but I'd like to avoid any 12 hour mishaps. :)

**Comment by panther2** [comment]
In brief:
Go to https://github.com/triplea-maps/world_war_ii_global and fork it
Go to your fork hit the 'Clone or Download' button, choose 'Download ZIP' and download the latest map files (you can be sure to start from the latest version now, to avoid conflicts).
Choose the xml that you want to modify from within the zip.
Apply your changes and rename the zip correctly.
Test your new xml by including it into the games directory of your current map installation in the current TripleA-installation.
When everything is fine get back to your fork.
Don't work directly in your master branch but create a working branch instead.
Apply the xml-file to the working branch by uploading it to the games directory and committing it.
When everything is fine merge the change to your fork's master branch (Using "Create pull request").
Once the change has been merged to you master you can create a pull request to the original repository. Just hit "Create pull request". Don't forget to give a description of what you want to add.
In the original repository a new pull request is opened then, that will be reviewable and discussable.
The repo admins will merge this  - from this time it will be included to the "official" map download.

Sounds complicated? No wizardry. Just see this tutorial:
https://guides.github.com/activities/hello-world/
for a description of what I have been talking about...

Once you have created your fork of the global map repository we can continue there in case you need further help.

**Comment by simon33-2** [comment]
Can this issue be closed?

**Comment by panther2** [comment]
IMHO yes.
